<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Invite\Module'                     => __DIR__ . '/Module.php',
    'Invite\Controller\IndexController' => __DIR__ . '/src/Invite/Controller/IndexController.php',
    'Invite\Model\Entity\Letter'        => __DIR__ . '/src/Invite/Model/Entity/Letter.php',
    'Invite\Service\Invite'             => __DIR__ . '/src/Invite/Service/Invite.php',
);
