<div id="page-title">
    <div id="page-title-inner">
        <!-- start: Container -->
        <div class="container">
            <h2><i class="ico-stats ico-white"></i>About Us</h2>
        </div>
        <!-- end: Container  -->
    </div>	
</div>
<div id="wrapper">
    <!--start: Container -->
    <div class="container">
        <!--start: Row -->
        <div class="row">
            <div class="span8">
                <!-- start: About Us -->
                <div id="about">
                    <div class="title"><h3>About Us</h3></div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                </div>	
                <!-- end: About Us -->

                <!-- start: History -->
                <div id="history">
                    <div class="title"><h3>History</h3></div>
                    <p>
                        <span class="dropcap">P</span>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                    <p>
                        <span class="dropcap color">P</span>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                    <p>
                        <span class="dropcap dark">P</span>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                    </p>
                </div>	
                <!-- end: History -->

                <!-- start: Team -->	
                <div id="team">

                    <div class="title"><h3>Team</h3></div>

                    <!-- start: Row -->
                    <div class="row">

                        <!-- start: About Member -->
                        <div class="span4">
                            <img alt="team member" src="img/team_member.jpg">
                            <div class="team-name">Lucas Luck <span> / Co-Founder, CEO</span></div>
                            <p>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
                            </p>
                            <div class="social_profiles">
                                <ul class="social-bookmarks">
                                    <li class="facebook"><a href="">facebook</a></li>
                                    <li class="flickr"><a href="">flickr</a></li>
                                    <li class="googleplus"><a href="#">googleplus</a></li>
                                    <li class="linkedin"><a href="#">linkedin</a></li>
                                    <li class="twitter"><a href="#">twitter</a></li>
                                    <li class="pinterest"><a href="#">pinterest</a></li>
                                </ul>
                            </div>	
                        </div>
                        <!-- end: About Member -->

                        <!-- start: About Member -->
                        <div class="span4">
                            <img alt="team member" src="img/team_member.jpg">
                            <div class="team-name">Lucas Luck <span> / Co-Founder, General Manager</span></div>
                            <p>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
                            </p>
                            <div class="social_profiles">
                                <ul class="social-bookmarks">
                                    <li class="facebook"><a href="">facebook</a></li>
                                    <li class="flickr"><a href="">flickr</a></li>
                                    <li class="googleplus"><a href="#">googleplus</a></li>
                                    <li class="linkedin"><a href="#">linkedin</a></li>
                                    <li class="twitter"><a href="#">twitter</a></li>
                                    <li class="pinterest"><a href="#">pinterest</a></li>
                                </ul>
                            </div>	
                        </div>
                        <!-- end: About Member -->	

                    </div>
                    <!-- end: Row -->

                </div>
                <!-- end: Team -->


            </div>	

            <div class="span4">

                <!-- start: Sidebar -->
                <div id="sidebar">

                    <!-- start: Skills -->
                    <div class="title"><h3>Our Skills</h3></div>
                    <ul class="progress-bar">
                        <li>
                            <h5>Web Design ( 40% )</h5>
                            <div class="meter"><span style="width: 148px;"></span></div><!-- Edite width here -->
                        </li>
                        <li>
                            <h5>Wordpress ( 80% )</h5>
                            <div class="meter"><span style="width: 296px;"></span></div><!-- Edite width here -->
                        </li>
                        <li>
                            <h5>Branding ( 100% )</h5>
                            <div class="meter"><span style="width: 370px;"></span></div><!-- Edite width here -->
                        </li>
                        <li>
                            <h5>SEO Optmization ( 60% )</h5>
                            <div class="meter"><span style="width: 222px;"></span></div><!-- Edite width here -->
                        </li>
                    </ul>
                    <!-- end: Skills -->

                    <!-- start: Tabs -->
                    <div class="title"><h3>Tabs</h3></div>

                    <ul class="tabs-nav">
                        <li class="active"><a href="#tab1"><i class="mini-ico-glass"></i> Tab 1</a></li>
                        <li><a href="#tab2"><i class="mini-ico-list"></i> Tab 2</a></li>
                        <li><a href="#tab3"><i class="mini-ico-pencil"></i> Tab 3</a></li>
                    </ul>

                    <div class="tabs-container">
                        <div id="tab1" class="tab-content" style="display: block;">1. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                        <div id="tab2" class="tab-content" style="display: none;">2. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                        <div id="tab3" class="tab-content" style="display: none;">3. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                    <!-- end: Tabs -->

                    <!-- start: Testimonials-->

                    <div class="testimonial-container">

                        <div class="title"><h3>Testimonials</h3></div>

                        <div data-autorotate="3000" class="testimonials-carousel" style="overflow: hidden; width: 100%;" role="application" aria-live="polite">	<a class="mr-rotato-next mr-rotato-disabled" href="#carousel-1-0" aria-disabled="true"></a>	<a class="mr-rotato-prev" href="#carousel-1-0"></a>

                            <ul class="carousel" id="carousel-1-0" style="margin-left: -300%; float: left; width: 400%; transition: margin-left 0.3s ease 0s;" aria-activedescendant="carousel-1-0-slide3">

                                <li class="testimonial" style="float: left; width: 25%;" role="tabpanel document" id="carousel-1-0-slide0" aria-hidden="true">
                                    <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                    <div class="testimonials-bg"></div>
                                    <div class="testimonials-author">Lucas Luck, <span>CEO</span></div>
                                </li>

                                <li class="testimonial" style="float: left; width: 25%;" role="tabpanel document" id="carousel-1-0-slide1" aria-hidden="true">
                                    <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                    <div class="testimonials-bg"></div>
                                    <div class="testimonials-author">Lucas Luck, <span>CTO</span></div>
                                </li>

                                <li class="testimonial" style="float: left; width: 25%;" role="tabpanel document" id="carousel-1-0-slide2" aria-hidden="true">
                                    <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                    <div class="testimonials-bg"></div>
                                    <div class="testimonials-author">Lucas Luck, <span>COO</span></div>
                                </li>

                                <li class="testimonial mr-rotato-active-slide" style="float: left; width: 25%;" role="tabpanel document" id="carousel-1-0-slide3" aria-hidden="false">
                                    <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                    <div class="testimonials-bg"></div>
                                    <div class="testimonials-author">Lucas Luck, <span>CMO</span></div>
                                </li>

                            </ul>

                        </div>

                    </div>

                    <!-- end: Testimonials-->

                </div>
                <!-- end: Sidebar -->

            </div>
        </div>
        <!--end: Row-->
    </div>
    <!--end: Container-->
</div>