<?php $this->headTitle('Settings'); ?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2 style=" width: 100%; padding: 10px 0px 5px 0px"><?php echo $this->Translate('Settings'); ?></h2>
        </div>
    </div>	
</div>

<div class="container">
    <div class="row">
        <div class="span3">
            <?php echo $this->ztbFlashMessenger('error'); ?>
            <?php echo $this->ztbFlashMessenger('success'); ?>
            <?php echo $this->ztbForm($this->form); ?>
        </div>
        <div class="span2">
            <h3>Info</h3>
            <ul>
                <li>
                    <h4>System balance: <b><?php echo $this->sbalance; ?>$</b></h4>
                </li>
                <li>
                    <h4>Users balance: <b><?php echo $this->ubalance; ?>$</b></h4>
                </li>
                <li>
                    <h4>Payment balance: <b><?php echo $this->pbalance; ?>$</b></h4>
                </li>
            </ul>
        </div>
    </div>
</div>