<div class="title"><h3>Withdraw:</h3></div>
<p>
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
</p>
<form class="form-horizontal" method="post" action="<?php echo $this->url('payment', array('action'=>'withdraw'));?>">
    <div class="control-group">
        <label for="ratefee" class="control-label">Balance:</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on">$</span>
                <input type="text" disabled="disabled" value="<?php echo $this->getUser()->getBalance(); ?>" name="ratefee" class="span2">
            </div>
        </div>
    </div>
    <div class="control-group">
        <label for="ratefee" class="control-label">Payza Email:</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on">@</span>
                <input type="text" value="<?php echo $this->getUser()->getEmail(); ?>" name="ratefee" class="span2">
            </div>
        </div>
    </div>
    <div class="control-group">
        <label for="ratefee" class="control-label">Amount:</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on">$</span>
                <input type="text" value="0" name="ratefee" class="span2">
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <div style="margin-left: 10px;" class="btn-group">
                <input type="submit" class="btn btn-primary span">
            </div>
        </div>
    </div>
</form>
