<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Contact\Module'                     => __DIR__ . '/Module.php',
    'Contact\Controller\IndexController' => __DIR__ . '/src/Contact/Controller/IndexController.php',
    'Contact\Form\Contact'               => __DIR__ . '/src/Contact/Form/Contact.php',
    'Contact\Model\Entity\Message'       => __DIR__ . '/src/Contact/Model/Entity/Message.php',
    'Contact\Service\Contact'            => __DIR__ . '/src/Contact/Service/Contact.php',
);
