<?php

namespace User\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Permission
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Permission extends EntityRepository
{
    
}
