<?php

namespace User\Model\Repository;

use Doctrine\ORM\EntityRepository;
use User\Model\Entity\User as UserEntity;

/**
 * User
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User extends EntityRepository
{

    public function getReferral(UserEntity $user, $level = 1)
    {
        
    }

}
