<?php

namespace User\Model\Repository;

use Doctrine\ORM\EntityRepository;
use User\Model\Entity\User as UserEntity;

/**
 * User
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User extends EntityRepository
{

    public function getReferral(UserEntity $user, $level = 1)
    {
        $alias = 'u0';
        $qb    = $this->getEntityManager()->createQueryBuilder();
        $qb->from($this->getEntityName(), $alias);
        $qb->where($qb->expr()->eq('u0.id', $user->getReferral()));
        for ($i = 1; $i < $level; $i++) {
            $alias = 'u' . $i;
            $qb->from($this->getEntityName(), $alias);
            $qb->andWhere($qb->expr()->eq('u' . ($i - 1) . '.referral', $alias . '.id'));
        }
        $qb->select($alias);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
