<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Account\Module'                       => __DIR__ . '/Module.php',
    'Account\Controller\PaymentController' => __DIR__ . '/src/Account/Controller/PaymentController.php',
    'Account\Controller\SettingController' => __DIR__ . '/src/Account/Controller/SettingController.php',
    'Account\Controller\TestController'    => __DIR__ . '/src/Account/Controller/TestController.php',
    'Account\Form\Setting'                 => __DIR__ . '/src/Account/Form/Setting.php',
    'Account\Model\Entity\Commision'       => __DIR__ . '/src/Account/Model/Entity/Commision.php',
    'Account\Model\Entity\Payment'         => __DIR__ . '/src/Account/Model/Entity/Payment.php',
    'Account\Model\Entity\Payout'          => __DIR__ . '/src/Account/Model/Entity/Payout.php',
    'Account\Model\Entity\Repayment'       => __DIR__ . '/src/Account/Model/Entity/Repayment.php',
    'Account\Model\Entity\Setting'         => __DIR__ . '/src/Account/Model/Entity/Setting.php',
    'Account\Service\Account'              => __DIR__ . '/src/Account/Service/Account.php',
    'Account\Service\Setting'              => __DIR__ . '/src/Account/Service/Setting.php',
);
