<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Account\Module'                 => __DIR__ . '/Module.php',
    'Account\Model\Entity\Payment'   => __DIR__ . '/src/Account/Model/Entity/Payment.php',
    'Account\Model\Entity\Payout'    => __DIR__ . '/src/Account/Model/Entity/Payout.php',
    'Account\Model\Entity\Repayment' => __DIR__ . '/src/Account/Model/Entity/Repayment.php',
    'Account\Service\Account'        => __DIR__ . '/src/Account/Service/Account.php',
);
