<?php $this->headTitle('Users Letters'); ?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2 style=" width: 100%; padding: 10px 0px 5px 0px">Users</h2>
        </div>
    </div>	
</div>
<div class="container">
    <?php if ($this->paginator): ?>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->Translate('User'); ?></th>
                    <th><?php echo $this->Translate('Title'); ?></th>
                    <th><?php echo $this->Translate('Created'); ?></th>
                    <th><?php echo $this->Translate('Updated'); ?></th>
                    <th width="125px"><?php echo $this->Translate('Actions'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $letter): ?>
                    <tr>
                        <td><?php echo $letter->getId(); ?></td>
                        <td><?php echo $letter->getUser()->getEmail(); ?></td>
                        <td><?php echo $letter->getTitle(); ?></td>
                        <td><?php echo $letter->getCreated()->format("Y-m-d H:i:s"); ?></td>
                        <td><?php echo $letter->getUpdated()->format("Y-m-d H:i:s"); ?></td>
                        <td>
                            <a class="btn btn-mini" href="#"><i class="icon-edit"></i> <?php echo $this->Translate('Edit'); ?></a>
                            <a class="btn btn-mini" href="#"><i class="icon-remove"></i> <?php echo $this->Translate('Remove'); ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
    <?php echo $this->PaginationControl($this->paginator, 'Sliding', 'application/partial/paginator.phtml', array ('params' => array ('action' => 'index'))); ?>
</div>