<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                         => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'     => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Entity\AbstractEntity'          => __DIR__ . '/src/Application/Entity/AbstractEntity.php',
    'Application\Service\GuestNavigationFactory' => __DIR__ . '/src/Application/Service/GuestNavigationFactory.php',
    'Application\Service\Result'                 => __DIR__ . '/src/Application/Service/Result.php',
    'Application\Service\UserNavigationFactory'  => __DIR__ . '/src/Application/Service/UserNavigationFactory.php',
);
