<?php $this->headTitle('Contact Us'); ?>
<?php $this->form->setAttribute('action', $this->url('contact')); ?>
<?php $this->form->get('submit')->setAttributes(array('class' => 'btn btn-primary'));?>
<?php $this->form->get('subject')->setAttributes(array('class' => 'span6'));?>
<?php $this->form->get('message')->setAttributes(array('class' => 'span6'));?>

<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2 style="width: 100%; padding: 10px 0px 5px 0px">Contact Us</h2>
        </div>
    </div>	
</div>

<div id="wrapper">		
    <div class="container">
        <div class="row">
            <div class="span3">
                <div class="title"><h3>Contact Info</h3></div>
                <p><b>Company Name</b></p>
                <p>30 South Park Avenue</p>
                <p>San Francisco, CA 94108, USA</p>	
                <p>Phone: (123) 456-7890</p>
                <p>Fax: +08 (123) 456-7890</p>
                <p>Email: contact@companyname.com</p>
                <p>Web: companyname.com</p>
            </div>
            <div class="span6">
                <div class="title"><h3>Contact Form</h3></div>
                <div id="contact-form">
                    <?php echo $this->ztbFlashMessenger('error'); ?>
                    <?php echo $this->ztbFlashMessenger('success'); ?>
                    <?php echo $this->ztbForm($this->form); ?>
                </div>
            </div>
            <!-- start: Social Sites -->
            <div class="span3">
                <div class="title"><h3>Follow US!</h3></div>
                <ul class="social-bookmarks">
                    <li class="facebook"><a href="#">facebook</a></li>
                    <li class="googleplus"><a href="#">googleplus</a></li>
                    <li class="linkedin"><a href="#">linkedin</a></li>
                    <li class="twitter"><a href="#">twitter</a></li>
                    <li class="youtube"><a href="#">youtube</a></li>
                </ul>
            </div>
            <!-- end: Social Sites -->
        </div>
    </div>
</div>
