<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAiRJREFUeNqcUjuIGkEYnl13XWMgICiiKQJC4EBQBEERQcTqtIiFFpLSVDGk92xs0oXrDCmU66MRFRMOBFNZ+ACLKDY2dooQFZ/rYzf/LI7Z20uafPAxM/9+3/+YHWq9XiOMRCKBCDiOuxJF8YsgCFYgxTDMUKvVvp/P5/dEk8lkEMQQAwKkwPP9ft+BBE9JAM4vD4dDEbY24BDHiI8+nU4Ik4Bl2Y/YbDKZHmSF2BOapnPkTDyM3HwW+s1ms5hMJqndbocWiwUCI+r3+0K5XH5BKhMffTweESaBWq3+Re5Do9Ego9GIDAYDcrlcFJx3REc8jxJAhU/FYpGHmZGc+XyeB11OmQCNRqNHjMfjsIyEyWQiYg6HwxPEfip1MO6fDuSEitl6vQ6Xv0ebzUasVqu4o6xSJ42gbPXMu1ardZzNZmi5XFLT6VSEWEupw6B6vd5l/nQ6rYPlDfC1z+e76nQ6HBbCfl+r1b5BPAua70RvtVoRg1ux2+0oHA7f6PX6m2g0yjkcDhXP89RgMJBaDQaDar/f/6pQKFynUqkf4M2VSqWvUgehUOgZLh4IBN5iM+DSUbvdlv632+2+xMbjsQBmvtlsfobjrcpisXyIRCLvoAqHH4l8xkqlIt22zWa7xKAABR2zOp3O2e12KTxC3Ol0qler1YMXiZM1Gg1pH4vFpNcoB8zPYi9OoNput+hv8Hg8UtV/fcdeyuv13p5v/n+Q/S3AAG8fjxvsSDpUAAAAAElFTkSuQmCC" alt="Roles">
        <span class="zdt-toolbar-info">
            Roles
        </span>
    </div>
    <div class="zdt-toolbar-detail">
        <span class="zdt-toolbar-info zdt-toolbar-info-heading">Your roles</span>
        <?php $roles = $this->collector->getRoles(); ?>
        <?php if ($roles): ?>
            <?php foreach ($roles as $role) : ?>
                <span class="zdt-toolbar-info ddt-toolbar-info"><?php echo $role; ?></span>
            <?php endforeach; ?>
        <?php else: ?>
            None
        <?php endif; ?>
    </div>
</div>

