<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Serif">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Boogaloo">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Economica:700,400italic">
        <!-- end: CSS -->

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!--[if IE 9]>
          <link href="/assets/css/styleie9.css" rel="stylesheet">
        <![endif]-->

        <?php echo $this->headTitle('REP ')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico')) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->plugin('HeadLink'); ?>
        <?php echo $this->plugin('HeadStyle'); ?>
        <?php echo $this->plugin('HeadScript'); ?>
        <?php echo $this->inlineScript() ?>
    </head>
    <body>
        <?php echo $this->partial('layout/partial/header.phtml'); ?>
        <?php echo $this->content; ?>
        <?php echo $this->render('layout/partial/footer.phtml'); ?>
    </body>
</html>
