<div class="title"><h3>Profit Calculator</h3></div>
<p>
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
</p>

<form class="navbar-form">
    <div class="btn-group">
        <label class="control-label span0" for="rate">Rate:</label>
    </div>
    <div class="btn-group">
        <div class="input-prepend span0" data-content="content" data-original-title="Rate" data-placement="top"  data-trigger="hover" data-toggle="popover">
            <span class="add-on"><i class="icon-user"></i></span>
            <input class="span1" id="rate" type="text" value="10">
        </div>
    </div>
    <div class="btn-group">
        <label class="control-label span0" for="rate">Rate Fee:</label>
    </div>
    <div class="btn-group">
        <div class="input-prepend span0" data-content="content" data-original-title="Rate" data-placement="top"  data-trigger="hover" data-toggle="popover">
            <span class="add-on">$</span>
            <input class="span1" id="fee" type="text" value="10">
        </div>
    </div>
    <div class="btn-group">
        <label class="control-label span0" for="rate">Profit:</label>
    </div>
    <div class="btn-group">
        <div class="input-prepend span0" data-content="content" data-original-title="Rate" data-placement="top"  data-trigger="hover" data-toggle="popover">
            <span class="add-on">$</span>
            <input class="span1" id="profit" type="text" value="10">
        </div>
    </div>
</form>


