<?php
if (empty($this->params)) {
    $this->params = array();
}
?>
<?php if ($this->pageCount > 1): ?>
    <div class="pagination pagination-centered">
        <ul>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $this->url($this->route, array_merge(array('page' => $this->previous), $this->params)); ?>">&laquo;</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">&laquo;</a></li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li><a href="<?php echo $this->url($this->route, array_merge(array('page' => $page), $this->params)); ?>"><?php echo $page; ?></a></li>
                <?php else: ?>
                    <li class="active"><a href="#"><?php echo $page; ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $this->url($this->route, array_merge(array('page' => $this->next), $this->params)); ?>">&raquo;</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">&raquo;</a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>