<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UserPage\Module'                     => __DIR__ . '/Module.php',
    'UserPage\Controller\IndexController' => __DIR__ . '/src/UserPage/Controller/IndexController.php',
    'UserPage\Model\Entity\Page'          => __DIR__ . '/src/UserPage/Model/Entity/Page.php',
    'UserPage\Model\Repository\Page'      => __DIR__ . '/src/UserPage/Model/Repository/Page.php',
    'UserPage\Service\UserPage'           => __DIR__ . '/src/UserPage/Service/Page.php',
);
