<?php

namespace UserPage\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Page
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Page extends EntityRepository
{
    
}
