<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Payment\Module'                     => __DIR__ . '/Module.php',
    'Payment\Controller\IndexController' => __DIR__ . '/src/Payment/Controller/IndexController.php',
    'Payment\Event'                      => __DIR__ . '/src/Payment/Event.php',
    'PayzaPayment\Service\PayzaService'  => __DIR__ . '/src/Payment/Gateway/AbstractGateway.php',
    'Payment\Service\PayzaService'       => __DIR__ . '/src/Payment/Gateway/PayzaService.php',
    'Account\Model\Entity\Payment'       => __DIR__ . '/src/Payment/Model/Entity/Payment.php',
    'Payment\Service\Payment'            => __DIR__ . '/src/Payment/Service/Payment.php',
    'Payment\View\Helper\PayzaButton'    => __DIR__ . '/src/Payment/View/Helper/PaymentButton.php',
);
