<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Payment\Module'                     => __DIR__ . '/Module.php',
    'Payment\Controller\IndexController' => __DIR__ . '/src/Payment/Controller/IndexController.php',
    'Payment\Event'                      => __DIR__ . '/src/Payment/Event.php',
    'Payment\Gateway\Payza'              => __DIR__ . '/src/Payment/Gateway/Payza.php',
    'Payment\Model\Entity\Transaction'   => __DIR__ . '/src/Payment/Model/Entity/Transaction.php',
    'Payment\Service\Payment'            => __DIR__ . '/src/Payment/Service/Payment.php',
    'Payment\View\Helper\PaymentButton'  => __DIR__ . '/src/Payment/View/Helper/PaymentButton.php',
);
