<?php $this->headTitle('Login'); ?>
<?php $this->form->setAttribute('action', $this->url('user', array('action' => 'login')));?>
<?php
    $email = $this->form->get('email')->setAttributes(array('class'=>'span12', 'placeholder' => 'Email'));
    $password = $this->form->get('password')->setAttributes(array('class'=>'span12', 'placeholder' => 'Password'));
?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2 style="text-align:center; width: 100%; padding: 10px 0px 5px 0px">Log in to your account</h2>
        </div>
    </div>	
</div>
<div class="container">
    <div class="row-fluid">
        <div class="lr-page span4 offset4">
            <div id="login-box">
                <!-- start: Row -->
                <div class="row-fluid">
                    <div class="span12" id="login-form">
                        <?php echo $this->ztbFlashMessenger('error'); ?>
                        <?php echo $this->form()->openTag($this->form);?>
                            <div class="row-fluid">
                                <?php echo $this->formHidden($this->form->get('csrf'));?>
                                <?php echo $this->formInput($email);?>
                                <?php echo $this->formInput($password);?>
                            </div>
                            <div class="row-fluid">
                                <div class="remember">
                                    <input type="checkbox" value="1" name="remember" id="remember"> Remember me!
                                </div>
                                <div class="forgot">
                                    <a href="<?php echo $this->url('user', array('action' => 'forgot'));?>">Forgot password?</a>
                                </div>
                            </div>	
                            <div class="actions">
                                <button class="btn btn-primary span12" type="submit">Login!</button>
                            </div>
                        <?php echo $this->form()->closeTag();?>
                    </div>
                </div>
            </div>
        </div>	
    </div>
</div>