<?php $this->headTitle('Register'); ?>
<?php $this->form->setAttribute('action', $this->url('user', array('action' => 'register'))); ?>
<?php
$email   = $this->form->get('email')->setAttributes(array('class'       => 'span12', 'placeholder' => 'Email'));
$password     = $this->form->get('password')->setAttributes(array('class'          => 'span12', 'placeholder'    => 'Password'));
$password_retype = $this->form->get('password_retype')->setAttributes(array('class'       => 'span12', 'placeholder' => 'Confirm Password'));
$referal      = $this->form->get('referal')->setAttributes(array('class'       => 'span12', 'placeholder' => 'Referal Code'));
?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2 style="text-align:center; width: 100%; padding: 10px 0px 5px 0px">Create your account</h2>
        </div>
    </div>	
</div>
<div class="container">
    <div class="row-fluid">
        <div class="lr-page span4 offset4">
            <div id="login-box">
                <div class="row-fluid">
                    <div class="span12" id="login-form">
                        <?php echo $this->ztbFlashMessenger('error'); ?>
                        <?php echo $this->form()->openTag($this->form); ?>
                        <div class="row-fluid">
                            <div class="control-group<?php echo $email->getMessages() ? ' error' : ''; ?>">
                                <?php echo $this->formInput($email); ?>
                                <?php echo $this->formElementErrors($email); ?>
                            </div>
                            <div class="control-group<?php echo $password->getMessages() ? ' error' : ''; ?>">
                                <?php echo $this->formInput($password); ?>
                                <?php echo $this->formElementErrors($password); ?>
                            </div>
                            <div class="control-group<?php echo $password_retype->getMessages() ? ' error' : ''; ?>">
                                <?php echo $this->formInput($password_retype); ?>
                                <?php echo $this->formElementErrors($password_retype); ?>
                            </div>
                            <div class="control-group<?php echo $referal->getMessages() ? ' error' : ''; ?>">
                                <?php echo $this->formInput($referal); ?>
                                <?php echo $this->formElementErrors($referal); ?>
                            </div>
                        </div>
                        <div class="actions">
                            <button class="btn btn-primary span12" type="submit">Create Account!</button>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>	
    </div>
</div>