<?php $this->headTitle('About Us');?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2><i class="ico-stats ico-white"></i>About Us</h2>
        </div>
    </div>	
</div>
<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="span">
                <div id="about">
                    <div class="title"><h3>About Us</h3></div>
                    <p>Real Estate Profit offers members two unique <b>opportunities to grow</b> their money.</p>
                    <p>First, by becoming a Rep and referring members to our site and second, by purchasing our high Rate of Return.</p>
                    <p>The high Rate of Return comes from Real Estate Investment Returns that our company works hard to earn for you in a short period of time.</p>
                    <h3>Real Estate Investment Returns</h3>
                    <p>We have over 15 years of experience in the real estate investment market and before investing we carefully analyze current and potential appreciation, inflation, supply and demand, capital improvements and numerous other factors to ensure we always make the best investments possible.</p>
                    <p>We enjoy access to a wide network of real estate agents and companies throughout the United States and the World that guarantees us low investment costs, quick re-sales and high returns.</p>
                    <p>Through our real estate investment system, we buy and sell real estate every day, sometimes making multiple purchases or sales at a time. By buying and selling every day, our company makes higher returns and by sharing these returns with our clients and letting them purchase our Rate of Return, we can expand our fund and real estate investment horizons, which means even higher returns for clients!</p>
                    <h3>Referral System</h3>
                    <p>Reps earn bonus commissions by inviting friends and relatives to our site. The more people you invite who join, the higher your earnings.</p>
                    <h3>Our Commitment </h3>
                    <p>At Real Estate Profit, we understand the concerns of investors and strive to provide our members with a unique profit opportunity that they won’t find anywhere else.</p>
                    <p>We will work closely with you to ensure your success. After all, your success truly is our success, too.</p>
                    <p>To help ensure your success, we offer the superior customer service, resources and profit opportunities you need to grow your money as well as our dedication to putting you first in every aspect of our business.</p>
                    <p>When you choose to join Real Estate Profit, you are selecting a membership site that is dedicated to meeting your needs and providing you with superior service.</p>
                    <p>Your satisfaction is our #1 priority.</p>
                </div>	
            </div>	
        </div>
    </div>
</div>