<?php $this->headTitle('Balance'); ?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2><i class="ico-stats ico-white"></i>Rate of Return</h2>
        </div>
    </div>	
</div>
<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="span2">
                <ul class="nav nav-tabs nav-stacked">  
                    <li><a href="<?php echo $this->url('page', array('action' => 'set-the-rate')); ?>">Set The Rate</a></li>
                    <li><a href="<?php echo $this->url('page', array('action' => 'purchase-the-rate')); ?>">Purchase the Rate</a></li>
                    <li class="active"><a href="<?php echo $this->url('page', array('action'  => 'balance')); ?>">Balance</a></li> 
                </ul>
            </div>
            <div class="span10">
                <div class="popover right" style="position: relative; display: block; max-width:100%">
                    <div class="arrow" style=" position: relative; top:88px"></div>
                    <div class="popover-content">
                        <div class="title"><h3>Balance</h3></div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <form class="form-horizontal">
                            <div class="control-group">
                                <label class="control-label" for="rate">Current Rate:</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on"><i class="icon-user"></i></span>
                                        <input class="span2" id="rate" value ="<?php echo $this->getUser()->getRate(); ?>" type="text" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="ratefee">Balance:</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input class="span2" name="ratefee" value ="<?php echo $this->getUser()->getBalance(); ?>" disabled="disabled" type="text" data-toggle="popover" data-trigger="hover" data-placement="left" data-original-title="Rate Fee" data-content="Rate Fee">
                                    </div>
                                    <div class="btn-group" style="margin-left: 10px;">
                                        <a href="#" class="btn btn-primary span">Withdraw</a>
                                    </div>
                                </div>

                            </div>
                        </form>
                        <br>

                        <div class="title"><h3>Activity:</h3></div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#payment"  data-toggle="tab">Payments Log</a></li>
                            <li><a href="#commisions"  data-toggle="tab">Referral Commissions Log</a></li>
                            <li><a href="#profile"  data-toggle="tab">Rate of Return Log</a></li>
                            <li><a href="#payouts"  data-toggle="tab">Withdraw Log</a></li>
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane active" id="payment">
                                <?php $payments = $this->getUser()->getPayments(); ?>
                                <?php if ($payments): ?>
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Fee</th>
                                                <th>Percent</th>
                                                <th>Profit</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($payments as $payment): ?>
                                                <tr>
                                                    <td><?php echo $payment->getCreated()->format("Y-m-d H:i:s"); ?></td>
                                                    <td><?php echo $payment->getAmount(); ?>$</td>
                                                    <td><?php echo $payment->getPercent() * 100; ?>%</td>
                                                    <td><?php echo $payment->getBalance(); ?></td>
                                                    <td><?php echo $payment->getStatus(); ?></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                <?php endif; ?>
                            </div>
                            <div class="tab-pane" id="commisions">
                                <?php $commisions = $this->getUser()->getCommisions(); ?>
                                <?php if ($commisions): ?>
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Profit</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($commisions as $commision): ?>
                                                <tr>
                                                    <td><?php echo $commision->getCreated()->format("Y-m-d H:i:s"); ?></td>
                                                    <td><?php echo $commision->getAmount(); ?>$</td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                <?php endif; ?>
                            </div>
                            <div class="tab-pane" id="payouts">
                                <?php $payouts = $this->getUser()->getPayouts(); ?>
                                <?php if ($payouts): ?>
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($payouts as $payout): ?>
                                                <tr>
                                                    <td><?php echo $payout->getCreated()->format("Y-m-d H:i:s"); ?></td>
                                                    <td><?php echo $payout->getAmount(); ?>$</td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                <?php endif; ?>
                            </div>
                            <div class="tab-pane" id="profile">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Username</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>@mdo</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>@fat</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td colspan="2">Larry the Bird</td>
                                            <td>@twitter</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>	
        </div>
    </div>
</div>