<?php $this->headTitle('Frequently Asked Questions'); ?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2><i class="ico-stats ico-white"></i>Frequently Asked Questions</h2>
        </div>
    </div>	
</div>
<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="span">
                <div class="title"><h3>Frequently Asked Questions</h3></div>
                <h3>How do I get started?</h3>
                <p>Simply click on the Join link at the top of this page to open your free account today.</p>
                <h3>Can I open multiple accounts?</h3>
                <p>No, each member is only allowed one account. Trying to circumvent this rule can result in the loss of all accounts, including their current balances and future earnings. </p>
                <h3>Can multiple people living in the same household have Real Estate Profit accounts?</h3>
                <p>Yes. Each member will have to have their own email address and payment processor, however.</p>
                <h3>How much money do I need to start?</h3>
                <p>Opening an account at Real Estate Profit is completely free. That means you can get started for whatever amount you want to spend – it could be as little as $5 if you want, though obviously the more money you deposit, the more money you could earn. </p>
                <h3>How much can I earn?</h3>
                <p>There are no set limits. This is truly an unlimited income opportunity.</p>
                <h3>Why should I trust you with my money?</h3>
                <p>We have over 15 years of experience and we carefully analyze each possible investment using our exclusive, proven-effective formula before deciding to invest or not. Also, our referral system provides members with an easy way to increase their earnings.</p>
                <h3>What makes this opportunity so unique?</h3>
                <p>As far as we know, no one else is offering members the opportunity to purchase a high rate of return that is based on real estate investment returns and a referral system.</p>
                <h3>When do I get my money?</h3>
                <p>You can withdraw your earnings from referrals and the purchase of our Rate of Return at anytime; however, once you’ve purchased the rate the fee can’t be withdrawn.</p>
                <h3>What is my risk?</h3>
                <p>As with most any type of profit opportunity, there is going to be some risk involved. However, we work hard to ensure that the risk with this profit opportunity is very, very low. We use our vast experience and knowledge to make the safest, yet most profitable real estate investments possible and we also provide members with the opportunity to make bonus commissions through our referral system.</p>
                <h3>I joined Real Estate Profit but did not receive my log-in information?</h3>
                <p>When someone joins Real Estate Profit we immediately send them an email containing their log-in and user information. If you did not receive this email:</p>
                <ul>
                    <li>It may have gone into your junk or spam folder. Please check there.</li>
                    <li>The email address you entered may contain an error. If you think this might be the case, please rejoin being careful to type the correct address.</li>
                </ul>
                <p>If neither of these two steps apply to you, please click here to have your log-in email resent to you immediately. If you do not receive the email this time, you may contact our customer support staff by clicking here.</p>

            </div>	
        </div>
    </div>
</div>