<?php $this->headTitle('How it works');?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2><i class="ico-stats ico-white"></i>How it works</h2>
        </div>
    </div>	
</div>
<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="span">
                <div class="title"><h3>Earning Money With Real Estate is Now as Easy as 1, 2, 3!</h3></div>
                <h3>Step 1 – Become a Rep.</h3>
                <p>Simply create a free account and you can start earning generous commissions by sharing our incredible income opportunity with others. </p>
                <h3>Step 2 – Purchase the Rate of Return.</h3>
                <p>We offer a variety of different rate products along with a system that is structured to maximize your returns. Plus, you can get started for as low as $5. </p>
                <h3>Step 3 – Sit back and watch your money grow!</h3>
                <p>Remember, good things come to those who wait. Prefer to earn quicker returns? Just purchase the Rate of Return on a daily basis.</p>
                <p>It’s really that easy. With Real Estate Profit you get two great ways to make money. Become a Rep and earn Bonus Commissions through our exclusive Referral System AND purchase our extremely high Rate of Return, which comes from Real Estate Investment Returns that our company works hard to earn for you </p>
                <p>So how much could you earn? Please see the Profit Calculator below to get a better idea.</p>
               <?php echo $this->partial('application/partial/calculator.phtml'); ?>
            </div>	
        </div>
    </div>
</div>