        <!-- start: Slider -->
        <div class="slider-wrapper">
            <div id="da-slider" class="da-slider">
                <div class="da-slide">
                    <h2>Twitter Bootstrap</h2>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <a href="#" class="da-link">Read more</a>
                    <div class="da-img"><img src="/assets/slider/img/twitter.png" alt="image01" /></div>
                </div>
                <div class="da-slide">
                    <h2>Responsive Design</h2>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <a href="#" class="da-link">Read more</a>
                    <div class="da-img"><img src="/assets/slider/img/responsive.png" alt="image02" /></div>
                </div>
                <div class="da-slide">
                    <h2>HTML5</h2>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <a href="#" class="da-link">Read more</a>
                    <div class="da-img"><img src="/assets/slider/img/html5.png" alt="image03" /></div>
                </div>
                <div class="da-slide">
                    <h2>CSS3</h2>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                    <a href="#" class="da-link">Read more</a>
                    <div class="da-img"><img src="/assets/slider/img/css3.png" alt="image04" /></div>
                </div>
                <nav class="da-arrows">
                    <span class="da-arrows-prev"></span>
                    <span class="da-arrows-next"></span>
                </nav>
            </div>
        </div>
        <!-- end: Slider -->
        <script type="text/javascript">
        jQuery(document).ready(function($){
            $('#da-slider').cslider({
                autoplay	: true,
                bgincrement	: 50
            });
        });
        </script>