<?php $this->headTitle('Letter invitation'); ?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2><i class="ico-stats ico-white"></i>Letter invitation</h2>
        </div>
    </div>	
</div>

<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="span2">
                <ul class="nav nav-tabs nav-stacked">  
                    <li><a href="<?php echo $this->url('page', array('action' => 'wellcome')); ?>">Wellcome Page</a></li>
                    <li class="active"><a href="<?php echo $this->url('page', array('action' => 'invitation')); ?>">Letter invitation</a></li> 
                </ul>
            </div>
            <div class="span10">
                <div class="popover right" style="position: relative; display: block; max-width:100%">
                    <div class="arrow" style=" position: relative; top:50px"></div>
                    <div class="popover-content">
                        <p style="text-align: right;">
                            <button class="btn btn-mini btn-primary" id="invite-letter-button" type="button" data-toggle="button">Edit</button>
                        </p>
                        <div class="title"><h3>Email Template:</h3></div>
                        <p data-savable="true" id="invite-letter">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                    </div>
                    <hr>
                    <div class="popover-content">
                        <div class="title"><h3>Send an Email Invitation:</h3></div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <div class="controls controls-row">
                            <textarea class="span5" type="text" id="invitelist" placeholder="Enter an email addresses"></textarea>
                            <button class="btn btn-primary span1" type="button" id="invitelist-button">Send</button>
                        </div>
                    </div>
                </div>
            </div>	
        </div>
    </div>
</div>