<?php $this->headTitle('Purchase the Rate'); ?>
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h2><i class="ico-stats ico-white"></i>Purchase the Rate</h2>
        </div>
    </div>	
</div>
<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="span2">
                <ul class="nav nav-tabs nav-stacked">  
                    <li><a href="<?php echo $this->url('page', array('action' => 'set-the-rate')); ?>">Set The Rate</a></li>
                    <li class="active"><a href="<?php echo $this->url('page', array('action' => 'purchase-the-rate')); ?>">Purchase the Rate</a></li>
                    <li><a href="<?php echo $this->url('page', array('action' => 'balance')); ?>">Balance</a></li> 
                </ul>
            </div>
            <div class="span10">
                <div class="popover right" style="position: relative; display: block; max-width:100%">
                    <div class="arrow" style=" position: relative; top:52px"></div>
                    <div class="popover-content">
                        <div class="title"><h3>Purchase the Rate:</h3></div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>

                        <form class="form-horizontal">
                            <div class="control-group">
                                <label class="control-label" for="rate">Current Rate of Return</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on"><i class="icon-user"></i></span>
                                        <input class="span2" id="rate" value ="0" type="text" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="ratefee">Rate Fee</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input class="span2" name="ratefee" value ="0" type="text" data-toggle="popover" data-trigger="hover" data-placement="left" data-original-title="Rate Fee" data-content="Rate Fee">
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="profit">Potential Return</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input class="span2" id="profit" value ="0" type="text" disabled="disabled">
                                    </div>
                                </div>
                            </div>
                        </form>

                        <ul class="pager">
                            <li class="next">
                                <a href="#">Purchase &rarr;</a>
                            </li>
                        </ul>
                    </div>


                </div>
            </div>	
        </div>
    </div>
</div>